name: vclibs
description: Let your flutter windows apps include vclibs.
version: 0.1.3
homepage: https://github.com/leanflutter/vclibs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: VclibsPluginCApi
