name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: cd example && flutter build windows -v
